### ISSUE TITLE
Wishlist for using Tcases as a library

### ISSUE THREAD

**Issue by tkruse** [Cornutum/tcases#14]
Follow-up from the PR discussion (#13).

Things I would wish for tcases-lib to rely on it as a java library robustly:
* [x] #15 Extract tcases.ant.TcasesTask to separate module to get rid of `ant` and logback dependencies (can still be bundled in a larger tcases jar, no change to current users if upgrading versions)
* [ ] ~~Shadow commons-lang3, Commons-collections4, to avoid version conflicts. Or simply drop dependencies if possible~~
* [x] #18 Extract package org.cornutum.tcases.io and file manipulation from Tcases.java to own maven module, to get rid of commons-io dependency. Also this removes the dependency to javax.xml modules and SAX in a Java9 jigsaw world.^
* [x] #17 Extract command-line argument parsing from Tcases.java to a separate maven module, it is bloat when using tcases-lib as a library (also paves the way for using libraries like picoli for the command-line parsing).
* [ ] ~~Provide dedicated public Tcases programming api, as opposed to internal apis (This mostly means extracting java interfaces from classes/methods like SystemInputDef, SystemTestDef, TCases.getTests and move them to a package like `.api`to minimize the visible surface of the library and have an official api, such that on version upgrades there is minimal rework to do for library users.~~
* [x] #20 clearly isolate FunctionTestDef generation from FunctionInputDef from SystemTestDef/SystemInputDef in the Api of Tcases.getTests(), for clients who do not need the System aggregate concept.

I might seem too harsh about the dependencies, but I know some users will reject libraries that look bloated with transitive dependencies. For Tcases as an independent executable application, they are all fine, of course.
Of course, the points could also be changed to: extract the purely combinatorial stuff (no ant, cli, xml) to a new lib module.

Other features I missed:
* [x] #21 Extend Tcases output to also include the "value properties" accumulated in testcases, those are valuable meta-information for debugging
* [x] #16 replace "NA" as String for "not applicable" with a value less likely to collide with values from the system domain (Possibly configurable for backwards compatibility)

If you consider any of those as worth doing, I suggest creating a separate ticket to discuss in more detail. I may have time to work on any of those.

**Comment by kerrykimbrough** [comment]
> Extract tcases.ant.TcasesTask to separate module to get rid of ant ... dependencies 

Good idea. I can easily do this. Although note that tcases-lib.jar will still depend on logback.

**Comment by kerrykimbrough** [comment]
> Shadow commons-lang3, Commons-collections4, to avoid version conflicts. 

Not sure what you mean by "shadow"

**Comment by kerrykimbrough** [comment]
> Extract package org.cornutum.tcases.io and file manipulation
> Extract command-line argument parsing 

These are reasonable ideas. Although many basic tests use file IO to create test inputs, so it will take some effort to refactor them.

**Comment by kerrykimbrough** [comment]
> clearly isolate FunctionInputDef from SystemInputDef, etc. for clients who do not need the System aggregate concept

At the API level, you can already do this using `ITestCaseGenerator.getTests`. But at the IO level, I don't the extra complexity of supporting 2 different levels of IO formats is worth the effort. Better: make it easier to create and deal with a **System** that contains only one **Function**.

**Comment by kerrykimbrough** [comment]
> Extend Tcases output to also include the "value properties" accumulated in testcases, those are valuable meta-information for debugging

If this is strictly for debugging, why not show value properties in the tcases.log file?

**Comment by kerrykimbrough** [comment]
> Make "NA" string configurable

That's a reasonable idea. I can see how that would be helpful in some situations.

**Comment by tkruse** [comment]
To shadow (or shade) dependencies means to extract all classes from a jar, modifying the bytecode to move them to a new package, and depending on them at their new package location. See https://maven.apache.org/plugins/maven-shade-plugin/, https://stackoverflow.com/questions/13620281, https://www.elastic.co/blog/to-shade-or-not-to-shade.

The logfile indeed shows value properties for each testcase, so it helps, though sadly I did not get the testcase Id:
```Completed test case=TestCaseDef[id=<null> ...```. So finding a specific testcase by searching for value combinations is a bit tedious. But I agree, given the logfile, the need for property output is less.
I was also thinking about using the value properties in the description of a testcase. I am not good at making up examples, but imagine testing some ancient tax form where you need to enter a numeric code to describe a person, e.g. Persontype(child-male: 0, child-female: 1, adult-male:2, child-female:3, ...). So the testcase might have this value: Persontype: 7). Then it's bothersome to look back at the inputdef to findout what '7' corresponds to. Output annotations can help, but where I already used meaningful properties already, additionally adding output annotations felt like unnecessary extra work.

Would you like me to proceed with creating individual tickets? I don't want to put pressure on you.

**Comment by tkruse** [comment]
>>   clearly isolate FunctionInputDef from SystemInputDef, etc. for clients who do not need the System aggregate concept
>
> At the API level, you can already do this using ITestCaseGenerator.getTests. But at the IO level, I don't think the extra complexity of supporting 2 different levels of IO formats is worth the effort. Better: make it easier to create and deal with a System that contains only one Function.

If you look at SystemTestDef getTests, you will see it calls

    // SystemInputDef inputDef,...
    for( Iterator<FunctionInputDef> functionDefs = inputDef.getFunctionInputDefs(); functionDefs.hasNext();)
      {
        ITestCaseGenerator functionGen = genDef.getGenerator( functionDef.getName());
        // ...   
        testDef.addFunctionTestDef( functionGen.getTests( functionDef, functionBase));
      }
    annotateTests( inputDef, testDef);

The problem here is that annotateTests() is called in the end only, meaning ITestCaseGenerator.getTests() does not handle annotations. So as a library User, while I can call ITestCaseGenerator.getTests() to get testcases, I still need to create a SystemInputDef to be able to call annotateTests() and see annotations. That does not seem clean.

**Comment by tkruse** [comment]
Actually if the remaining dependencies are just commons-lang3, commons-collections, and slf4j, that's probably good enough for a test library. So no need to bother with shading dependencies.

**Comment by kerrykimbrough** [comment]
> while I can call ITestCaseGenerator.getTests() to get testcases, I still need to create a SystemInputDef to be able to call annotateTests() and see annotations. 

Good point. I've added issue #20 to address this.

**Comment by kerrykimbrough** [comment]
> Extend Tcases output to also include the "value properties" accumulated in testcases

Good point. I've added issue #21 to address this.

**Comment by kerrykimbrough** [comment]
> Provide dedicated public Tcases programming api, as opposed to internal apis

It seems to me that Tcases classes already have a well-defined public API. I'm not sure why any additional interfaces would be needed.

**Comment by tkruse** [comment]
> It seems to me that Tcases classes already have a well-defined public API. I'm not sure why any additional interfaces would be needed.

Looking some more, I agree. The classes already have a good split of public vs private methods. Using interfaces consistently would allow library users to provide their own implementations in some cases, but I currently see no good use-case anyway. Still some classes like RandSeq or TupleRef look 'internal' to me (they might not be), and some libraries try to be explicit about which classes are public and which ones are not. Same as Java9 modules not exposing all classes, even if the classes are 'public', they become invisible to jar consumers. But that's not a real problem in the case of Tcases, so we can remove that item from the wishlist.

**Comment by tkruse** [comment]
clsogin because all items have new issues
